### ISSUE TITLE
Connect to scorebot without socket().wait()

### ISSUE THREAD

**Issue by Funeoz** [bombsimon/hltv-python#2]
Hi,

So I've been working with our implementation for some time now. I would like to know if there's a way to connect to the scorebot without wait() because each time I try without this function, it just doesn't connect to the scorebot. Also, the fact that wait() blocks the thread is a bit annoying for me.

**Comment by bombsimon** [comment]
The current solution uses the blocking `sio` implementation. There is a non blocking implementation with an [`AsyncClient`](https://python-socketio.readthedocs.io/en/latest/api.html#socketio.AsyncClient). I don't have too much time to spend on this project but I could try to find some time to look into an implementation.

Please feel free to create a PR with an async implementation, the API looks identical except it's non blocking with the `AsyncClient`.

**Comment by Funeoz** [comment]
Okay Thanks !

**Comment by bombsimon** [comment]
@Funeoz I did a quick switch to the `AsyncClient` from `socektio`, please see [example](https://github.com/bombsimon/hltv-python/blob/master/examples/kill_log.py) for usage and how to run the socket stream in the background.

I didn't make any other methods async but I don't think they benefit much from being so. Please let me know if you run in to any trouble!

**Comment by Funeoz** [comment]
I will try it and tell you if I have any issues. Thanks for the modification !
