### ISSUE TITLE
is there any possible way to register async function?

### ISSUE THREAD

**Issue by Soulbadguy54** [bombsimon/hltv-python#7]
Example contains lines:

```python
@classmethod
def on_connect(cls):
    """
    A simple callback to ensure we got connected.
    """
    print("connected!")
```

and:

`live_score.on(live_score.EVENT_CONNECT, kill_feed.on_connect)`
What if the "on_connect" etc functions should be async? For write something in DB as example.

And additional. What should i do to get info from 2+ matches in the same time? I tried to make several instanses of Livescore in cycle, but the first await socket.wait() blocks everything. So, during iteration i can get data only from the first match (1st iter)

**Comment by Soulbadguy54** [comment]
Yes, thx for help. It helps a lot. Did you face the "packet queue is empty. Aborting" error?

And unstable connection. Every 10-30 seconds i get disconnect event and autoreconnection.
Why is it so unstable? Should we try to use sync socketio?

**Comment by bombsimon** [comment]
Cool! I've pushed a change now sending `list_id` to all callbacks.

I've seen packet queue empty a few times but not nearly as often as you're describing. Usually I see it if I don't handle `SIGINT` properly and the server disconnects. When this happens, the socket will reconnect automatically as well.

I don't wanna make this sync again, this was changed to async in #2. I think it's more flexible to use the async version so we can allow both async/await and threading.

**Comment by bombsimon** [comment]
Now that we do support async callbacks and also passes the list_id, would you mind closing this issue?

If you want to troubleshoot instability I think that's better to do in a separate issue with some reproducible examples and benchmarks. I'm running the example in this repository when I test and I don't get disconnected as often.

**Comment by Soulbadguy54** [comment]
Thx for help and response. Can you answer me, what is SiGINT?

**Comment by bombsimon** [comment]
`SIGINT` is a [Signal](https://en.wikipedia.org/wiki/Signal_(IPC)#POSIX_signals) of the type `INT` (interrupt), usually what is sent to a process when you hit Ctrl + C.

**Comment by bombsimon** [comment]
Closing this, please open a new issue if you have other feature requests or if you suspect any bugs!
